/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Wed Dec  6 15:36:18 GMT 2017
 * 
 * To automatically register this VPI wrapper with a Verilog simulator use:
 *     #include "vpi_wrapper_initialize_image.h"
 *     void (*vlog_startup_routines[])() = { initialize_image_vpi_register, 0u };
 */
#include <stdlib.h>
#include <vpi_user.h>
#include "bdpi.h"

/* the type of the wrapped function */
void initialize_image();

/* VPI wrapper function */
PLI_INT32 initialize_image_calltf(PLI_BYTE8 *user_data)
{
  
  /* call the imported C function */
  initialize_image();
  
  return 0;
}

/* VPI wrapper registration function */
void initialize_image_vpi_register()
{
  s_vpi_systf_data tf_data;
  
  /* Fill in registration data */
  tf_data.type = vpiSysTask;
  tf_data.tfname = "$imported_initialize_image";
  tf_data.calltf = initialize_image_calltf;
  tf_data.compiletf = 0u;
  tf_data.sizetf = 0u;
  tf_data.user_data = "$imported_initialize_image";
  
  /* Register the function with VPI */
  vpi_register_systf(&tf_data);
}
