//
// Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
//
// On Tue Dec  5 23:03:56 GMT 2017
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMultiTb(CLK,
		 RST_N);
  input  CLK;
  input  RST_N;

  // register c
  reg [31 : 0] c;
  wire [31 : 0] c$D_IN;
  wire c$EN;

  // register cnt
  reg [31 : 0] cnt;
  wire [31 : 0] cnt$D_IN;
  wire cnt$EN;

  // register fh
  reg [31 : 0] fh;
  wire [31 : 0] fh$D_IN;
  wire fh$EN;

  // register lfsr1_r
  reg [31 : 0] lfsr1_r;
  wire [31 : 0] lfsr1_r$D_IN;
  wire lfsr1_r$EN;

  // register lfsr2_r
  reg [31 : 0] lfsr2_r;
  wire [31 : 0] lfsr2_r$D_IN;
  wire lfsr2_r$EN;

  // register starting
  reg starting;
  wire starting$D_IN, starting$EN;

  // ports of submodule dut
  wire [71 : 0] dut$multiply;
  wire [39 : 0] dut$multiply_m2;
  wire [31 : 0] dut$multiply_m1;
  wire [5 : 0] dut$multiply_k;

  // rule scheduling signals
  wire WILL_FIRE_RL_rule_tb;

  // remaining internal signals
  reg [31 : 0] TASK_fopen___d3;

  // submodule dut
  mkDrum dut(.CLK(CLK),
	     .RST_N(RST_N),
	     .multiply_k(dut$multiply_k),
	     .multiply_m1(dut$multiply_m1),
	     .multiply_m2(dut$multiply_m2),
	     .multiply(dut$multiply),
	     .RDY_multiply());

  // rule RL_rule_tb
  assign WILL_FIRE_RL_rule_tb = c == 32'd0 && !starting ;

  // register c
  assign c$D_IN = c + 32'd1 ;
  assign c$EN = WILL_FIRE_RL_rule_tb ;

  // register cnt
  assign cnt$D_IN = 32'd1 ;
  assign cnt$EN = cnt == 32'd0 ;

  // register fh
  assign fh$D_IN = TASK_fopen___d3 ;
  assign fh$EN = cnt == 32'd0 ;

  // register lfsr1_r
  assign lfsr1_r$D_IN =
	     lfsr1_r[0] ?
	       { 1'd1,
		 lfsr1_r[31:8],
		 ~lfsr1_r[7],
		 lfsr1_r[6],
		 ~lfsr1_r[5],
		 lfsr1_r[4],
		 ~lfsr1_r[3:1] } :
	       { 1'd0, lfsr1_r[31:1] } ;
  assign lfsr1_r$EN = WILL_FIRE_RL_rule_tb ;

  // register lfsr2_r
  assign lfsr2_r$D_IN =
	     lfsr2_r[0] ?
	       { 1'd1,
		 lfsr2_r[31:8],
		 ~lfsr2_r[7],
		 lfsr2_r[6],
		 ~lfsr2_r[5],
		 lfsr2_r[4],
		 ~lfsr2_r[3:1] } :
	       { 1'd0, lfsr2_r[31:1] } ;
  assign lfsr2_r$EN = WILL_FIRE_RL_rule_tb ;

  // register starting
  assign starting$D_IN = 1'd0 ;
  assign starting$EN = starting ;

  // submodule dut
  assign dut$multiply_k = 6'd32 ;
  assign dut$multiply_m1 = 32'd2 ;
  assign dut$multiply_m2 = 40'd2 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        c <= `BSV_ASSIGNMENT_DELAY 32'd0;
	cnt <= `BSV_ASSIGNMENT_DELAY 32'd0;
	fh <= `BSV_ASSIGNMENT_DELAY 32'd0;
	lfsr1_r <= `BSV_ASSIGNMENT_DELAY 32'd1;
	lfsr2_r <= `BSV_ASSIGNMENT_DELAY 32'd1;
	starting <= `BSV_ASSIGNMENT_DELAY 1'd1;
      end
    else
      begin
        if (c$EN) c <= `BSV_ASSIGNMENT_DELAY c$D_IN;
	if (cnt$EN) cnt <= `BSV_ASSIGNMENT_DELAY cnt$D_IN;
	if (fh$EN) fh <= `BSV_ASSIGNMENT_DELAY fh$D_IN;
	if (lfsr1_r$EN) lfsr1_r <= `BSV_ASSIGNMENT_DELAY lfsr1_r$D_IN;
	if (lfsr2_r$EN) lfsr2_r <= `BSV_ASSIGNMENT_DELAY lfsr2_r$D_IN;
	if (starting$EN) starting <= `BSV_ASSIGNMENT_DELAY starting$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    c = 32'hAAAAAAAA;
    cnt = 32'hAAAAAAAA;
    fh = 32'hAAAAAAAA;
    lfsr1_r = 32'hAAAAAAAA;
    lfsr2_r = 32'hAAAAAAAA;
    starting = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (cnt == 32'd0)
	begin
	  TASK_fopen___d3 = $fopen("file1.txt", "w");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rule_tb)
	$display("    Result = %b \n    Expect = %b \n   ",
		 dut$multiply,
		 dut$multiply);
    if (RST_N != `BSV_RESET_VALUE) if (WILL_FIRE_RL_rule_tb) $display("\n");
    if (RST_N != `BSV_RESET_VALUE) if (c != 32'd0) $finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkMultiTb

